pipeline 
{
  agent any 
  stages 
  {
    stage('Test') 
    {
      steps 
      {
        echo 'this is test phase'
      }
      stage('Deploy') 
      {
      steps 
        {
        echo 'this is deploy phase'
      }
    }
  }
}
}
