pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        echo 'this is test phase'
      }
      stage('Deploy') {
      steps {
        echo 'this is deploy phase'
      }
    }
  }
}
